trigger:
- none

resources:
  repositories:
    - repository: azpfilter
      type: github
      name: microsoft/azure-pipeline-filter
      endpoint: githubConnection

pool:
  vmImage: ubuntu-latest

variables:
  filter.modified.globs: 'a/**/*.txt,a/**/*.js'
  filter.prbody.heading: '#### Test Options'
  filter.prbody.optionIndex: 0

stages:
- stage: Filter
  jobs:
  - job: Check
    steps:
    - checkout: azpfilter
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - script: npm ci
      displayName: NPM Install
    - script: node src/main.mjs
      env:
        FILTER_GITHUBPAT: $(filter.githubPAT)
      name: execution
      displayName: Execution
- stage: Main
  dependsOn: Check
  # dependencies.$(StageName).outputs['$(JobName).$(TaskName).$(VariableName)']
  condition: and(succeeded(), ne(dependencies.Filter.outputs['Check.execution.skipsubsequent'], 'true'))
  jobs:
  - job: Main
    steps:
    - script: echo end
      displayName: 'Run main test'